// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pviafrbehuottgpsrxcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2aWFmcmJlaHVvdHRncHNyeGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTQ0NDUsImV4cCI6MjA3MzM3MDQ0NX0.EGxfZXFq7kcYu3m8sXln6JXhZ5Tup9bXgQvYz2STj2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});