// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jciaxdlqrmnvkqsxpypt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaWF4ZGxxcm1udmtxc3hweXB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTQ4MDgsImV4cCI6MjA3MzUzMDgwOH0.exRs13mepeYZ_pBugh7b7ug-nV081s5UaCq2cz3SD-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});